palette = "google_dark"

shell = ["sh"]

# Timeout for starship to scan files (in milliseconds)
scan_timeout = 30

command_timeout = 1000

[palettes.google_dark]
dark_grey = "#333333"
mid_grey = "#444444"
light_grey = "#555555"
white = "#ffffff"
yellow = "#ffff00"
red = "#ff0000"
blue = "#0000ff"
purple = "#800080"

format = """\
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$docker_context\
$nix_shell\
$conda\
$aws\
$gcloud\
$env_var\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$character\
"""

[aws]
disabled = false
format = '[[](bg:#444444 fg:#333333)[on](bg:#444444 fg:white) $symbol$profile(\($region\))[](bg:#333333 fg:#444444)]($style)'
symbol = " "
style = "bold bg:#444444 fg:yellow"

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[](bg:#555555 fg:#333333)$symbol$percentage[](bg:#333333 fg:#555555)]($style)"
[[battery.display]]
threshold = 10
style = "bg:#555555 fg:red"

[character]
disabled = false
format = "$symbol "
success_symbol = "[[](bg:green fg:#333333)](fg:green)"
error_symbol = "[[](bg:red fg:#333333)](fg:red)"
vicmd_symbol = "[[](fg:green bg:#333333)](bg:green fg:#000000)"

[cmake]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = "喝 "
style = "bg:#444444 fg:blue"

[cmd_duration]
disabled = false
min_time = 2_000
format = "[[](bg:#555555 fg:#333333)took $duration[](bg:#333333 fg:#555555)]($style)"
show_milliseconds = false
style = "bold bg:#555555 fg:yellow"
show_notifications = false
min_time_to_notify = 45_000

[conda]
disabled = false
truncation_length = 1
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$environment[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:green"
ignore_base = true

[crystal]
disabled = false
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:red"

[dart]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:blue"

[directory]
disabled = false
truncation_length = 3
truncate_to_repo = true
format = "[[](bg:light_grey fg:dark_grey)$path [](bg:dark_grey fg:light_grey)]($style)([[](bg:light_grey fg:dark_grey)$read_only[](bg:dark_grey fg:light_grey)]($read_only_style))"
style = "italic bg:light_grey fg:cyan"
read_only = ""
read_only_style = "bg:light_grey fg:red"

[git_state]
disabled = false
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold bg:#555555 fg:yellow"
format = '\([[](bg:#555555 fg:#333333)$state( $progress_current/$progress_total )[](bg:#333333 fg:#555555)]($style)\)'


[git_status]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_branch]
disabled = true

[docker_context]
disabled = false
symbol = " "
style = "bold bg:#444444 fg:blue"
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$context[](bg:#333333 fg:#444444)]($style)"
only_with_files = true

[dotnet]
disabled = true
format = "[[](bg:#444444 fg:#333333)$symbol$version( ﯑ $tfm)[](bg:#333333 fg:#444444)]($style)"
symbol = "•NET "
style = "bg:#444444 fg:blue"
heuristic = true

[elixir]
disabled = true
format = '[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$versi[on](bg:#444444 fg:white) \(OTP $otp_version\)[](bg:#333333 fg:#444444)]($style)'
symbol = " "
style = "bg:#444444 fg:purple"

[elm]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:cyan"

[env_var]
disabled = false
symbol = ""
style = "bold bg:#555555 fg:#000000"
format = "([[](bg:#555555 fg:#333333)[with](bg:#555555 fg:white) $symbol$env_value[](bg:#333333 fg:#555555)]($style))"

[erlang]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:red"

[gcloud]
disabled = true
# format = '[[](bg:#444444 fg:#333333)[on](bg:#444444 fg:white) $symbol$account(\($region\))[](bg:#333333 fg:#444444)]($style)'
format = '[[](bg:#444444 fg:#333333)$symbol$project[](bg:#333333 fg:#444444)]($style)'
# Optional: Shorten account to 8 chars
symbol = " "
style = "bold bg:#444444 fg:blue"

[golang]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:cyan"

[helm]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = "⎈ "
style = "bg:#444444 fg:white"

[hostname]
disabled = false
ssh_only = true
trim_at = "."
format = "[[](bg:#555555 fg:#333333)($style)$hostname(bg:#555555 fg:white)[](bg:#333333 fg:#555555)]($style)"
style = "bold dimmed bg:#555555 fg:green"

[java]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
style = "dimmed bg:#444444 fg:red"
symbol = " "

[jobs]
disabled = false
threshold = 1
format = "[[](bg:#555555 fg:#333333)$symbol$number[](bg:#333333 fg:#555555)]($style)"
symbol = "✦"
style = "bold bg:#555555 fg:blue"

[julia]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:purple"

[kubernetes]
disabled = true
symbol = "☸ "
format = '[[](bg:#444444 fg:#333333)$symbol$context( \($namespace\)) in[](bg:#333333 fg:#444444)]($style)'
style = "bold bg:#444444 fg:cyan"

[line_break]
disabled = true

[memory_usage]
disabled = true
threshold = 75
format = "[[](bg:#555555 fg:#333333)[via](bg:#555555 fg:white) $symbol$ram( | $swap)[](bg:#333333 fg:#555555)]($style)"
style = "bold dimmed bg:#555555 fg:white"
symbol = " "

[hg_branch]
disabled = true
symbol = " "
style = "bg:#555555 fg:purple"
format = "[[](bg:#555555 fg:#333333)[on](bg:#555555 fg:white) $symbol$branch[](bg:#333333 fg:#555555)]($style)"
truncation_symbol = "…"

[nim]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:yellow"

[nix_shell]
disabled = false
format = '[[](bg:#555555 fg:#333333)[via](bg:#555555 fg:white) $symbol$state( \($name\))[](bg:#333333 fg:#555555)]($style)'
symbol = " "
style = "bold bg:#555555 fg:blue"
impure_msg = "impure"
pure_msg = "pure"

[nodejs]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:green"

[ocaml]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = "🐫 "
style = "bg:#444444 fg:yellow"

[package]
disabled = true
format = "[[](bg:#444444 fg:#333333)[is](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:208"
display_private = false

[perl]
disabled = true
symbol = " "
style = "bg:#444444 fg:149"
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"

[php]
disabled = true
symbol = " "
style = "bg:#444444 fg:147"
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"

[purescript]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = "<=> "
style = "bg:#444444 fg:white"

[ruby]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:red"

[rust]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = " "
style = "bg:#444444 fg:red"

[shlvl]
disabled = true
threshold = 2
format = "[[](bg:#555555 fg:#333333)$symbol$shlvl[](bg:#333333 fg:#555555)]($style)"
symbol = "↕"
style = "bold bg:#555555 fg:yellow"

[singularity]
disabled = false
format = '[[](bg:#444444 fg:#333333)$symbol\[$env\][](bg:#333333 fg:#444444)]($style)'
symbol = ""
style = "bold dimmed bg:#444444 fg:blue"

[swift]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = "ﯣ "
style = "bg:#444444 fg:202"

[status]
disabled = true
format = "[[](bg:#555555 fg:#333333)$symbol$status[](bg:#333333 fg:#555555)]($style)"
symbol = " ✖"
style = "bold bg:#555555 fg:red"

[terraform]
disabled = true
format = '[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol\($workspace\)[](bg:#333333 fg:#444444)]($style)'
symbol = "ﰉ "
style = "bold bg:#444444 fg:105"

[time]
disabled = true
format = "[[](bg:#555555 fg:#333333)at $time[](bg:#333333 fg:#555555)]($style)"
style = "bold bg:#555555 fg:yellow"
use_12hr = false
time_format = ""
utc_time_offset = "local"
time_range = "-"

[username]
disabled = true
format = "[[](bg:#555555 fg:#333333)$user [in](bg:#555555 fg:white)[](bg:#333333 fg:#555555)]($style)"
style_root = "bold bg:#555555 fg:red"
style_user = "bold bg:#555555 fg:yellow"
show_always = false

[zig]
disabled = true
format = "[[](bg:#444444 fg:#333333)[via](bg:#444444 fg:white) $symbol$version[](bg:#333333 fg:#444444)]($style)"
symbol = "↯ "
style = "bg:#444444 fg:yellow"

[custom.jj]
description = "The current jj status"
detect_folders = [".jj"]
symbol = "🥋 "
style = "bold bg:light_grey fg:purple"
format = "[[](bg:light_grey fg:dark_grey)(bg:light_grey fg:white) $symbol$output[](bg:dark_grey fg:light_grey)]($style)"
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color never --limit 1 --no-pager --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    concat(
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    ),
    if(empty, "(empty)"),
    coalesce(
      truncate_end(29, description.first_line(), "…"),
    )
  )
'
'''

[custom.jjstate]
when = "jj --ignore-working-copy root"
symbol = "±"
style = "bold bg:light_grey fg:purple"
format = "[[](bg:light_grey fg:dark_grey)(bg:light_grey fg:white)$symbol$output[](bg:dark_grey fg:light_grey)]($style)"
command = '''
jj log -r@ -n1 --ignore-working-copy --no-graph --no-pager -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" ' ${1}m ${2}+ ${3}-' | sd " 0." ""
'''

[custom.git_commit]
when = "test ! -d .jj && git rev-parse --verify HEAD >/dev/null 2>&1"
command = "git rev-parse --short HEAD"
format = '([[](bg:light_grey fg:dark_grey)$output[](bg:dark_grey fg:light_grey)]($style))'
style = "bold bg:light_grey fg:green"

[custom.git_metrics]
when = "! jj --ignore-working-copy root"
command = "starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"
style = ""

[custom.git_branch]
when = """ root=$(git rev-parse --show-toplevel 2>/dev/null) && test ! -d "$root/.jj" """
description = "Show git branch only if not in a jj repo"
style = "bold bg:light_grey fg:purple"
format = "[[](bg:light_grey fg:dark_grey)(bg:light_grey fg:white)$symbol$output[](bg:dark_grey fg:light_grey)]($style)"
command = "git branch --show-current 2>/dev/null"
symbol = " "

[custom.fig]
shell = ["zsh", "--no-rcs", "-c"]
format = "[[](bg:light_grey fg:dark_grey)  $output[](bg:dark_grey fg:light_grey)]($style)"
command = """ echo "$PWD" | sed -n "s|^/google/src/cloud/$USER/\\([^/]*\\).*|\\1|p" """
when = """ [[ "$PWD" == "/google/src/cloud/$USER"* ]] """
style = "bold bg:mid_grey fg:blue"
