[user]
email = "me@brongan.com"
name = "Brennan Tracy"

[ui]
default-command = "log"
diff-formatter = ":git"
editor = "nvim"
pager = "delta"
paginate = "auto"
merge-editor = "diffconflicts"

[merge-tools.nvim-diff]
program = "nvim"
args = ["-d", "$left", "$right"]

[merge-tools.nvim-merge]
program = "nvim"
merge-args = ["$output"]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[aliases]
cma = ["commit", "-m"]
init = ["git", "init", "--colocate"]
push = ["util", "exec", "--", "bash", "-c", """
set -e
desc=$(jj log -r @ -T description --no-graph --color never)
is_empty=$(jj log -r @ -T empty --no-graph --color never)
if [ -n "$desc" ] && [ "$is_empty" = "false" ]; then
    jj new
fi
bookmark=$(jj log -r 'ancestors(@) & bookmarks()' -n 1 -T bookmarks --no-graph --color never | awk '{print $1}' | tr -d '*')
if [ -z "$bookmark" ]; then
    exit 1
fi
jj bookmark set "$bookmark" -r @-
jj git fetch
jj git push --bookmark "$bookmark"
"""]
