[user]
email = "me@brongan.com"
name = "Brennan Tracy"

[[--scope]]
--when.repositories = ["/usr/local/google"]

[--scope.user]
email = "brennantracy@google.com"

[ui]
default-command = "log"
diff-formatter = ":git"
editor = "nvim"
pager = "delta"
paginate = "auto"
merge-editor = "diffconflicts"
show-cryptographic-signatures = true

[template-aliases]
'format_short_cryptographic_signature(sig)' = '''
  if(sig,
    sig.status(),
    "(no sig)",
  )
'''

[merge-tools.nvim-diff]
program = "nvim"
args = ["-d", "$left", "$right"]

[merge-tools.nvim-merge]
program = "nvim"
merge-args = ["$output"]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[aliases]
cma = ["commit", "-m"]
init = ["git", "init", "--colocate"]
fetch = ["git", "fetch"]
push = ["git", "push"]
sync = ["git", "fetch", "--all-remotes"]

[signing]
backend = "ssh"
behavior = "drop"
key = "~/.ssh/commit_signing.pub"

[signing.backends.ssh]
allowed-signers = "~/.ssh/allowed_signers"

[git]
sign-on-push = true

