[user]
email = "me@brongan.com"
name = "Brennan Tracy"

[ui]
default-command = "log"
diff-formatter = ":git"
editor = "nvim"
pager = "delta"
paginate = "auto"
merge-editor = "diffconflicts"

[merge-tools.nvim-diff]
program = "nvim"
args = ["-d", "$left", "$right"]

[merge-tools.nvim-merge]
program = "nvim"
merge-args = ["$output"]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[aliases]
cma = ["commit", "-m"]
init = ["git", "init", "--colocate"]
fetch = ["git", "fetch"]
push = ["git", "push"]
sync = ["git", "fetch", "--all-remotes"]

