#!/usr/bin/env bash

set -ux

MONITORS=( $(xrandr --query -display ${DISPLAY} | grep " connected " | awk '{ print$1 }' | tr '\n' ' ') )
if [[ ${#MONITORS[@]} -eq 1 ]]; then
	bspc monitor "${MONITORS[0]}" -d I II III IV V
	bspc rule -a Caprine desktop=^3
	bspc rule -a discord desktop=^3
elif  [[ ${#MONITORS[@]} -eq 2 ]]; then
	bspc monitor "${MONITORS[0]}" -d I II III 
	bspc monitor "${MONITORS[1]}" -d IV V VI
	bspc rule -a Caprine desktop=^4
	bspc rule -a discord desktop=^4
else
	bspc monitor "${MONITORS[1]}" -d I II III
	bspc monitor "${MONITORS[2]}" -d IV V VI
	# laptop display
	bspc monitor "${MONITORS[0]}" -d VII 
	# Why is work laptop 13 inch 4k
	xrandr --output "${MONITORS[0]}" --mode 1920x1080
fi
bspc rule -a Nightly deskop=^2
bspc rule -a Google-chrome desktop=^2

# border color
# bspc config normal_border_color "$(get_xrdb background)"
# bspc config focused_border_color "$(get_xrdb color12)"
bspc config border_width          3
bspc config window_gap            12
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Rofi state=floating
bspc rule -a Peek state=floating
bspc rule -a Zathura state=tiled
bspc rule -a firefox state=tiled
bspc rule -a Nightly state=tiled

# pointer
xsetroot -cursor_name left_ptr

steamlib=~/Games/SteamLibrary 
if [[ -d $steamlib ]]; then
	mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')
	for game in $mygames; do
		bspc rule -a steam_app_$game desktop=^2 state=fullscreen
	done
fi

hsetroot -fill ~/Desktop/CyberneticBackground.jpg

kitty &
if  command -v "firefox-nightly"  &> /dev/null; then
	firefox-nightly &
else
	google-chrome &
fi

if command -v "caprine"  &> /dev/null; then
	caprine &
fi
if command -v "discord"  &> /dev/null; then
	discord &
fi

if ! systemctl cat xorg.target 2&> /dev/null; then
	sxhkd &
	picom &
	dunst &
	launch_polybar.sh
fi

