#! /bin/sh

bspc monitor  DP-2 -d I II III 
bspc monitor DP-4 -d IV V VI

# border color
# bspc config normal_border_color "$(get_xrdb background)"
# bspc config focused_border_color "$(get_xrdb color12)"
bspc config border_width         3
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Rofi state=floating
bspc rule -a Peek state=floating
bspc rule -a Zathura state=tiled

# pointer
xsetroot -cursor_name left_ptr

steamlib=/games/SteamLibrary    # path to your steamlibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^2 state=fullscreen
done

kitty &
firefox-nightly &
caprine &
discord &
