#!/usr/bin/env bash

disconnected=""
wireless_connected=""
ethernet_connected="🖧"

while true; do
    found=false
    for interface in /sys/class/net/*; do
        if [[ $(< ${interface}/operstate ) == "up" && $(readlink -f ${interface}) != /sys/devices/virtual/*  ]]; then
            found=true
            if [[ "${interface##*/}" == e* ]]; then
                echo "$ethernet_connected"
            else
                echo "$wireless_connected" "$(iwgetid -r)"
            fi
        fi
    done
    if [[ "$found" == true ]]; then
        sleep 25
    else
        echo $disconnected
        sleep 5
    fi
done

