#!/bin/bash

if command -v kitty; then
    TERMINAL=kitty
else
    TERMINAL=xterm
fi

if command -v paru; then
    $TERMINAL paru
elif command -v yay; then
    $TERMINAL yay
elif command -v pacman; then
    $TERMINAL sudo pacman -Syu
elif command -v apt; then
    $TERMINAL sudo apt update -y && sudo apt upgrade -y
else
    exit 1
fi

