#!/bin/bash

if command -v kitty; then
    TERMINAL=kitty
else
    TERMINAL=xterm
fi

if command -v paru; then
    $TERMINAL paru
elif command -v yay; then
    $TERMINAL yay
else
    $TERMINAL sudo pacman -Syu
fi

